# Generated by Django 4.0.4 on 2022-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField(unique=True)),
                ('ename', models.CharField(max_length=30)),
                ('sal', models.IntegerField()),
                ('deptno', models.IntegerField()),
            ],
        ),
    ]
